/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;
import com.mycompany.videoclub.proyecto.Cliente;
import com.mycompany.videoclub.proyecto.ClientePrime;
import com.mycompany.videoclub.proyecto.Gestor;
import javax.swing.JOptionPane;
/**
 *
 * @author cesar
 */
public class ClienteNormal extends javax.swing.JFrame {

    private  Gestor videoClub;
    private  Cliente cliente;
    /**
     * Creates new form clienteNormal
     * @param club
     * @param client
     */
    public ClienteNormal(Gestor club, Cliente client) {
        
        initComponents();
        this.setLocationRelativeTo(null);
        videoClub = club;
        cliente=client;
        etiquetaBienvenidos();
    }
    private void etiquetaBienvenidos(){
        
        jLabel1.setText("Bienvenidos "+cliente.getNombreUsuario());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        irInicio = new javax.swing.JButton();
        botonMostrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        irInicio.setText("EXIT");
        irInicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        irInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irInicioActionPerformed(evt);
            }
        });

        botonMostrar.setText("MOSTRAR CATALOGO");
        botonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarActionPerformed(evt);
            }
        });

        jLabel1.setText("Bienvenido");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(irInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel1)
                .addGap(0, 283, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(botonMostrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(57, 57, 57)
                .addComponent(botonMostrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 232, Short.MAX_VALUE)
                .addComponent(irInicio)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void irInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irInicioActionPerformed
        // TODO add your handling code here:
        int i = JOptionPane.showConfirmDialog(this, "Seguro que quiere salir"); 
        if (i == 0)
        {
            Portada port = new Portada(videoClub);
            port.setVisible(true);
            this.dispose();
        }
        
    }//GEN-LAST:event_irInicioActionPerformed

    private void botonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarActionPerformed
        // TODO add your handling code here:
        Catalogo cat = new Catalogo(videoClub,cliente);
        cat.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_botonMostrarActionPerformed
    
     
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonMostrar;
    private javax.swing.JButton irInicio;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
