/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import com.mycompany.videoclub.proyecto.Cliente;
import com.mycompany.videoclub.proyecto.Pelicula;
import com.mycompany.videoclub.proyecto.Gestor;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author cesar
 */
public class PelisPosesion extends javax.swing.JFrame {

    private Cliente cliente;
    private Gestor videoClub;
    /**
     * Creates new form PelisPosesion
     */
    public PelisPosesion(Gestor club, Cliente client) {
        initComponents();
        this.setLocationRelativeTo(null);
        videoClub = club;
        cliente = client;
        agregarmispelis();
    }
    private void agregarmispelis()
    {
        //cliente.mostrarPeliculasEnPosesion();
        ArrayList<String> pelis = cliente.peliculasArrendadas();

        for(int i = 0; i < pelis.size(); i++){
            combo.addItem(pelis.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        combo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdatos = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        botoninfo = new javax.swing.JButton();
        botondevolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(553, 259));

        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });

        txtdatos.setColumns(20);
        txtdatos.setRows(5);
        jScrollPane1.setViewportView(txtdatos);

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 1, 14)); // NOI18N
        jLabel1.setText("MIS PELICULAS");

        jButton1.setText("VOLVER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        botoninfo.setText("INFO");
        botoninfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoninfoActionPerformed(evt);
            }
        });

        botondevolver.setText("DEVOLVER");
        botondevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botondevolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botondevolver)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combo, 0, 278, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botoninfo)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botoninfo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(botondevolver)
                .addGap(21, 21, 21)
                .addComponent(jButton1)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ClienteNormal volver = new ClienteNormal(videoClub,cliente);
        volver.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botoninfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoninfoActionPerformed
        ArrayList<String> pelis = cliente.peliculasArrendadas();
        
        int indice = combo.getSelectedIndex();  
        String nombrepeli  = "NOSEBUCO";
        
        for(int i = 0; i <= indice; i++){
            nombrepeli = pelis.get(i);
        }
        
        Pelicula peli = videoClub.buscarPeliculaPorNombre(nombrepeli);
        //txtdatos.setText("\n \n \n \n \n"+peli.getTitulo()+peli.getGenero() +peli.getSinopsis() +peli.getExistencias() +peli.getRating() +peli.getPrecioArriendo());
        
        txtdatos.setLineWrap(true);  // Habilita el ajuste de línea
        txtdatos.setWrapStyleWord(false);// Desactiva el ajuste de palabra
        txtdatos.setText(
        "Título: " + peli.getTitulo() + "\n" +
        "Género: " + peli.getGenero() + "\n" +
        "Sinopsis: " + peli.getSinopsis() + "\n" +
        "Existencias: " + peli.getExistencias() + "\n" +
        "Rating: " + peli.getRating() + "\n" +
        "Precio de Arriendo: " + peli.getPrecioArriendo());
    }//GEN-LAST:event_botoninfoActionPerformed

    private void botondevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botondevolverActionPerformed
        ArrayList<String> pelis = videoClub.obtenerNombresPeliculas();
        
        int indice = combo.getSelectedIndex();  
        String nombrepeli  = "NOSEBUCO";
        
        for(int i = 0; i <= indice; i++){
            nombrepeli = pelis.get(i);
        }
        
        Pelicula peli = videoClub.buscarPeliculaPorNombre(nombrepeli);
        
        int i = JOptionPane.showConfirmDialog(this, "Seguro que quiere DEVOLVER ESTA PELICULA"); 
        if (i == 0)
        {
            
            cliente.devolverPelicula(videoClub, nombrepeli);
            JOptionPane.showMessageDialog(this, "PELICULA DEVUELTA");
              
        }
    }//GEN-LAST:event_botondevolverActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botondevolver;
    private javax.swing.JButton botoninfo;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtdatos;
    // End of variables declaration//GEN-END:variables
}
